#####
# Author: Wendell
# Date: 2016/10/13
# 
# Because ansible is base on python ,so python must be installed fist. This playbook will skip the process of python installation
#
#####
- hosts: azclient
  user: wuenhouse
  become: True
  tasks:
    #install pip
    - easy_install: name=pip state=latest
    #install pip module
    - pip: name={{ item }}
      with_items:
        - config
        - docutils
        - lockfile
        - python-daemon
        - numpy
        - pyinotify
        - tornado
        - requests
        - pymongo==2.8
        - luigi==1.0.19
        - scipy

    install development tools    
    - name: install the Development tools package group
      yum: name="@Development tools" state=present

    install development env
    - name: install yum depency lib
      yum: name={{ item }} state=latest
      with_items:
        - openssl-devel
        - bzip2-devel
        - ncurses-devel
        - sqlite-devel
        - zlib-devel

    - name: Create file
      become: False
      file: path=~/working/source_package state=directory
    - name: download libevent source package
      become: False
      get_url:
        url: https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
        dest: /tmp/
    - name: download tumx source package
      become: False
      get_url:
        url: https://github.com/tmux/tmux/releases/download/2.2/tmux-2.2.tar.gz
        dest: /tmp/
